UserRegistration/Controllers/MyWelcomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MySql.Data.MySqlClient;
using UserRegistration.Models;
 

namespace UserRegistration.Controllers
{
    public class MyWelcomeController : Controller
    {
        public IActionResult Index()
        {
            EndUserDetailsModel md = new EndUserDetailsModel();
            return View(md);
        }
        public IActionResult Test()
        {
            string connstr = "server=localhost;port=3306;database=dotnetdemo;user=root;password=anupam;";
            string name = ";";
            using (MySqlConnection conn = new MySqlConnection(connstr))
            {
                conn.Open();
                MySqlCommand cmd = new MySqlCommand("select * from user",conn);
                using (MySqlDataReader dr = cmd.ExecuteReader())
                {
                    while(dr.Read())
                    {
                        name = dr.GetString("name");
                    }
                }

            }

                return View();
        }
        [HttpGet]
        public IActionResult EmailDetail()
        {
            return View(new EndUserDetailsModel());
        }

        [HttpPost]
        public IActionResult EmailDetail(EndUserDetailsModel mod)
        {
            //return RedirectToAction("FileUpload");
            return View(new EndUserDetailsModel());
        }

         
        public IActionResult FileUpload()
        {
            return View();
        }

        // [HttpGet]
        //public IActionResult Postjson()
        //{
        //    return null;
        //}


         
        public IActionResult Postjson( )
        {
            var files = Request.Form.Files;
            filesModel fmodel = new filesModel();
            fmodel.files = new List<FileUploadModel>();
            //FileUploadModel fl = new FileUploadModel();
            //fl.name = "twitter.png";
            //fl.size = 600000;
            //fl.url = "Download?fname=" + fl.name;
            //fl.thumbnail_url = "https://jquery-file-upload.appspot.com/image%2Fpng/195107973/twitter.png";
            
            //fl.delete_type = "DELETE";
            //fl.delete_url = "";
            //fmodel.files.Add(fl);

            foreach(var file in files)
            {
                savetodisk(file);
                fmodel.files.Add(new FileUploadModel {
                    name=file.FileName,
                    size=file.Length,
                    url= "Download?fname=" +file.FileName,
                    thumbnailUrl= "Download?fname=" + file.FileName,
                    deleteType = "DELETE",
                    deleteUrl = "delete?fname=" + file.FileName

                });
            }


            // string k = @"{'files': [  {'name': 'picture1.jpg',  'size': 902604, 'url': 'http:\/\/ example.org\/ files\/ picture1.jpg', 'thumbnailUrl': 'http:\/\/ example.org\/ files\/ thumbnail\/ picture1.jpg', 'deleteUrl': 'http:\/\/ example.org\/ files\/ picture1.jpg','deleteType': 'DELETE'  }]}";
            return Json(fmodel);
           
        }

        private void savetodisk(IFormFile file)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), file.FileName);
            using (FileStream source =System.IO.File.Open(path,FileMode.Create))
            { 
                file.CopyTo(source);
            }
        }

        public FileResult Download(string fname)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), fname);
            byte[] fileBytes = System.IO.File.ReadAllBytes(path);
            string fileName = fname;
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, fileName);
        }

        public void delete(string fname)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), fname);
            System.IO.File.Delete(path);
        }
    }
}

UserRegistration/Views/MyWelcome/CheckHistory.cshtml
@model EndUserDetailsModel
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />

    <script src="~/js/modernizr.js" type="text/javascript"></script>

    <script src="~/js/classie.js" type="text/javascript"></script>

    <style>
        button {
            padding: 1em 2em;
            outline: none;
            font-weight: 600;
            border: none;
            color: #fff;
            background: green;
            -webkit-border-radius: 49px 48px 48px 48px;
            -moz-border-radius: 49px 48px 48px 48px;
            border-radius: 49px 48px 48px 48px;
        }

        .dialog,
        .dialog__overlay {
            width: 100%;
            height: 100%;
            top: 0;
            left: 0;
        }

        .dialog {
            position: fixed;
            display: -webkit-flex;
            display: flex;
            -webkit-align-items: center;
            align-items: center;
            -webkit-justify-content: center;
            justify-content: center;
            pointer-events: none;
        }

        .dialog__overlay {
            position: absolute;
            z-index: 1;
            background: rgba(55, 58, 71, 0.9);
            opacity: 0;
            -webkit-transition: opacity 0.3s;
            transition: opacity 0.3s;
            -webkit-backface-visibility: hidden;
        }

        .dialog--open .dialog__overlay {
            opacity: 1;
            pointer-events: auto;
        }

        .dialog__content {
            width: 50%;
            max-width: 560px;
            min-width: 290px;
            background: #fff;
            padding: 4em;
            text-align: center;
            position: relative;
            z-index: 5;
            opacity: 0;
        }

        .dialog--open .dialog__content {
            pointer-events: auto;
        }

        /* Content */
        .dialog h2 {
            margin: 0;
            font-weight: 400;
            font-size: 2em;
            padding: 0 0 2em;
            margin: 0;
        }


        .dialog--open .dialog__overlay {
            -webkit-transition-duration: 0.8s;
            transition-duration: 0.8s;
        }

        .dialog--close .dialog__overlay {
            -webkit-transition-duration: 0.5s;
            transition-duration: 0.5s;
        }

        .dialog__content {
            padding: 0;
            background: transparent;
        }

        .dialog.dialog--open .dialog__content {
            opacity: 1;
        }

        .morph-shape {
            position: absolute;
            width: calc(100% + 4px);
            height: calc(100% + 4px);
            top: -2px;
            left: -2px;
            z-index: -1;
        }

            .morph-shape svg rect {
                stroke: #fff;
                stroke-width: 2px;
                stroke-dasharray: 1680;
            }

        .dialog--open .morph-shape svg rect {
            -webkit-animation: anim-dash 0.6s forwards;
            animation: anim-dash 0.6s forwards;
        }

        .dialog-inner {
            opacity: 0;
            background: #fff;
        }

        .dialog--open .dialog-inner {
            padding: 4em;
            opacity: 1;
            -webkit-transition: opacity 0.85s 0.35s;
            transition: opacity 0.85s 0.35s;
        }

        .dialog.dialog--open h2 {
            -webkit-animation: anim-elem-1 0.7s ease-out both;
            animation: anim-elem-1 0.7s ease-out both;
        }

        .dialog.dialog--open button {
            -webkit-animation: anim-elem-2 0.7s ease-out both;
            animation: anim-elem-2 0.7s ease-out both;
        }

        keyframes anim-dash {
            0%

        {
            stroke-dashoffset: 1680;
        }

        100% {
            stroke-dashoffset: 0;
        }

        }

        -webkit-keyframes anim-dash {
            0%

        {
            stroke-dashoffset: 1680;
        }

        100% {
            stroke-dashoffset: 0;
        }

        }

        /* Inner elements animations */

        -webkit-keyframes anim-elem-1 {
            0%

        {
            opacity: 0;
            -webkit-transform: translate3d(-150px, 0, 0);
        }

        100% {
            opacity: 1;
            -webkit-transform: translate3d(0, 0, 0);
        }

        }

        keyframes anim-elem-1 {
            0%

        {
            opacity: 0;
            -webkit-transform: translate3d(-150px, 0, 0);
            transform: translate3d(-150px, 0, 0);
        }

        100% {
            opacity: 1;
            -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
        }

        }

        -webkit-keyframes anim-elem-2 {
            0%

        {
            opacity: 0;
            -webkit-transform: translate3d(150px, 0, 0);
        }

        100% {
            opacity: 1;
            -webkit-transform: translate3d(0, 0, 0);
        }

        }

        keyframes anim-elem-2 {
            0%

        {
            opacity: 0;
            -webkit-transform: translate3d(150px, 0, 0);
            transform: translate3d(150px, 0, 0);
        }

        100% {
            opacity: 1;
            -webkit-transform: translate3d(0, 0, 0);
            transform: translate3d(0, 0, 0);
        }
        }
    </style>



</head>
<body>
    <div class="button-wrap"><button onclick="return false;" data-dialog="somedialog" class="trigger">Check History</button></div>


    <div id="somedialog" class="dialog dialog--close">
        <div class="dialog__overlay"></div>
        <div class="dialog__content">
            <div class="morph-shape">
                <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 560 280" preserveAspectRatio="none">
                    <rect x="3" y="3" fill="none" width="556" height="276"></rect>
                </svg>
            </div>
            <div class="dialog-inner">
                <h2><strong>Hi @Model.firstname, </strong> We are reviewing your previous submission. We will notify you once approved.</h2>
                <div><button class="action" onclick="return false;" data-dialog-close="a">Close</button></div>
            </div>
        </div>
    </div>
    <script type="text/javascript">

        ; (function (window) {

            'use strict';

            var support = { animations: Modernizr.cssanimations },
                animEndEventNames = { 'WebkitAnimation': 'webkitAnimationEnd', 'OAnimation': 'oAnimationEnd', 'msAnimation': 'MSAnimationEnd', 'animation': 'animationend' },
                animEndEventName = animEndEventNames[Modernizr.prefixed('animation')],
                onEndAnimation = function (el, callback) {
                    var onEndCallbackFn = function (ev) {
                        if (support.animations) {
                            if (ev.target != this) return;
                            this.removeEventListener(animEndEventName, onEndCallbackFn);
                        }
                        if (callback && typeof callback === 'function') { callback.call(); }
                    };
                    if (support.animations) {
                        el.addEventListener(animEndEventName, onEndCallbackFn);
                    }
                    else {
                        onEndCallbackFn();
                    }
                };

            function extend(a, b) {
                for (var key in b) {
                    if (b.hasOwnProperty(key)) {
                        a[key] = b[key];
                    }
                }
                return a;
            }

            function DialogFx(el, options) {
                this.el = el;
                this.options = extend({}, this.options);
                extend(this.options, options);
                this.ctrlClose = this.el.querySelector('[data-dialog-close]');
                this.isOpen = false;
                this._initEvents();
            }

            DialogFx.prototype.options = {
                // callbacks
                onOpenDialog: function () { return false; },
                onCloseDialog: function () { return false; }
            }

            DialogFx.prototype._initEvents = function () {
                var self = this;

                // close action
                this.ctrlClose.addEventListener('click', this.toggle.bind(this));

                // esc key closes dialog
                document.addEventListener('keydown', function (ev) {
                    var keyCode = ev.keyCode || ev.which;
                    if (keyCode === 27 && self.isOpen) {
                        self.toggle();
                    }
                });

                this.el.querySelector('.dialog__overlay').addEventListener('click', this.toggle.bind(this));
            }

            DialogFx.prototype.toggle = function () {
                var self = this;
                if (this.isOpen) {
                    classie.remove(this.el, 'dialog--open');
                    classie.add(self.el, 'dialog--close');

                    onEndAnimation(this.el.querySelector('.dialog__content'), function () {
                        classie.remove(self.el, 'dialog--close');
                    });

                    // callback on close
                    this.options.onCloseDialog(this);
                }
                else {
                    classie.add(this.el, 'dialog--open');

                    // callback on open
                    this.options.onOpenDialog(this);
                }
                this.isOpen = !this.isOpen;
            };

            // add to global namespace
            window.DialogFx = DialogFx;

        })(window);

        /* call */


        window.onload = function loaded() {
            var dlgtrigger = document.querySelector('[data-dialog]');
            somedialog = document.getElementById(dlgtrigger.getAttribute('data-dialog'));
            dlg = new DialogFx(somedialog);

            dlgtrigger.addEventListener('click', dlg.toggle.bind(dlg));

        };


    </script>
</body>
</html>

UserRegistration/Views/MyWelcome/FileUpload.cshtml
@{
    ViewData["Title"] = "welcomepost";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="center">
    @Html.Partial("_FileUpload")
    </div>

<style>
    .center {
       margin:auto;
        width: 80%;
        height: 500px;
        border: 1px solid #808080;
        padding: 10px;
        background-color: rgb(255, 153, 0);
        -webkit-box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        -moz-box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        -webkit-border-radius: 49px 48px 48px 48px;
        -moz-border-radius: 49px 48px 48px 48px;
        border-radius: 49px 48px 48px 48px;
    }
</style>

UserRegistration/Views/MyWelcome/Index.cshtml
@model EndUserDetailsModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layouthome.cshtml";
}

@using (Html.BeginForm("emaildetail", "MyWelcome", FormMethod.Post))
{
    @Html.AntiForgeryToken();
<section id="moving" style="width:90%;">
    <video class="vdoclass" autoplay muted loop>
        <source src="~/Video/video.mp4" type="video/mp4" />
    </video>
    <div id="panel" class="paneldiv">
        <ul style="list-style:none;padding-top:2em;">
            <li> @Html.TextBoxFor(m => m.email, htmlAttributes: new { @class = "form_field_index", placeholder = "Email Address" })</li>
            <li> @Html.TextBoxFor(m => m.password, htmlAttributes: new { @class = "form_field_index", placeholder = "Password" })</li>
            <li>
                <table>
                    <tr>
                        <td><input type="submit" class="btn btn-primary buttonmiddle" value="Login" id-="Login" onclick="location.href = 'mywelcome/EmailDetail';" /></td>
                        <td> <input type="submit" class="btn btn-primary buttonmiddle" value="Sign Up" id-="signup" onclick="location.href = 'register/index'; return false;"  /></td>
                    </tr>
                </table>
            </li>
            <li style=" margin: 10px 0;"> </li>
            <li style=" margin: 10px 0;float:right;"></li>
        </ul>

    </div>
    @*<div id="vdodata" class="blocktext">
            <h1>You can upload your documents here. Easy to start</h1>
            <input type="submit" class="start-btn" value="Start here" />
        </div>*@
    @*<div>
            <div class="centertop">
                <ul style="list-style:none">

                    <li> @Html.TextBoxFor(m => m.email, htmlAttributes: new { @class = "form_field_index", placeholder = "Email Address" })</li>
                    <li> @Html.TextBoxFor(m => m.password, htmlAttributes: new { @class = "form_field_index", placeholder = "Password" })</li>
                    <li><div style="text-align:center;margin-top:10px"><input type="submit" class="btn btn-primary" value="Login" id-="Start" /></div></li>
                </ul>

            </div>
            <div class="centerbelow">
                <ul style="list-style:none">


                    <li> @Html.TextBoxFor(m => m.email, htmlAttributes: new { @class = "form_field_index", placeholder = "Email Address" })</li>
                    <li> @Html.TextBoxFor(m => m.password, htmlAttributes: new { @class = "form_field_index", placeholder = "Password" })</li>
                    <li><div style="text-align:center;margin-top:10px"><input type="submit" class="btn btn-primary" value="Login" id-="Start" /></div></li>
                </ul>

            </div>
            <div class="validation-section">
                @Html.ValidationMessageFor(m => m.email)
            </div>
            <div style="text-align:center;">

            </div>
        </div>*@

    <div class="centerdiv">
        <ul style="list-style:none">


            <li>
                <div class="centertop">


                </div>
            </li>
            <li>
                <div class="centermiddle">


                </div>
            </li>
            <li>
                <div class="centerbelow">


                </div>
                <img id="condone" src="~/images/considerdone.png" style="width:90%;height:50px;" />
            </li>
        </ul>
    </div>
</section>

}

<style>
    .form_field_index {
        width: 90%;
        background: #ffffff;
        color: black;
        font: inherit;
        box-shadow: 0 6px 10px 0 rgba(0, 0, 0, .9);
        border: 0;
        outline: 0;
        padding: 22px 18px;
        margin-top: 10px;
        opacity: .9;
        height: 30px;
    }

    .centerdiv {
        margin-left: auto;
        margin-top: 20px;
        margin-right: -50px;
        width: 30%;
        height: 500px;
        padding: 10px;
        opacity: .9;
        /*-webkit-box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        -moz-box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);*/
        -webkit-border-radius: 49px 48px 48px 48px;
        -moz-border-radius: 49px 48px 48px 48px;
        border-radius: 49px 48px 48px 48px;
    }
    /*.centertop {
        margin-left: auto;
        margin-top: 40px;
        margin-right: -50px;
        width: 30%;
        height: 170px;
        border: 1px solid #808080;
        padding: 10px;
        opacity: .9;
        background-color: rgb(255, 153, 0);
        -webkit-box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        -moz-box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        box-shadow: -3px -8px 52px 4px rgba(63,64,63,0.53);
        -webkit-border-radius: 49px 48px 48px 48px;
        -moz-border-radius: 49px 48px 48px 48px;
        border-radius: 49px 48px 48px 48px;
    }*/
    .centertop {
        width: 100%;
        height: 90px;
        border: 1px solid #808080;
        padding: 10px;
        opacity: .9;
        background-color: rgb(255, 153, 0);
        -webkit-box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        -moz-box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        -webkit-border-radius: 49px 48px 48px 0px;
        -moz-border-radius: 49px 48px 48px 0px;
        border-radius: 49px 48px 48px 0px;
    }

    .centermiddle {
        margin-top: 90px;
        width: 100%;
        height: 90px;
        border: 1px solid #808080;
        padding: 10px;
        opacity: .9;
        background-color: rgb(255, 153, 0);
        -webkit-box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        -moz-box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        -webkit-border-radius: 0px 48px 0px 48px;
        -moz-border-radius: 0px 90px 0px 90px;
        border-radius: 0px 90px 0px 90px;
    }

    .centerbelow {
        margin-top: 90px;
        width: 100%;
        height: 90px;
        border: 1px solid #808080;
        padding: 10px;
        opacity: .9;
        background-color: rgb(255, 153, 0);
        -webkit-box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        -moz-box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        box-shadow: -3px -8px 52px 4px rgba(255,255,255,0.53);
        -webkit-border-radius: 49px 0px 48px 48px;
        -moz-border-radius: 49px 0px 48px 48px;
        border-radius: 49px 0px 48px 48px;
    }


    .vdoclass {
        width: 100%;
        position: absolute;
        z-index: -100;
        transform: translateX(-1%) translateY(0%);
        -ms-transform: translateX(-1%) translateY(0%);
        -moz-transform: translateX(-1%) translateY(0%);
        -webkit-transform: translateX(-1%) translateY(-20%);
    }

    .blocktext {
        position: absolute;
        margin-left: 40%;
        margin-right: auto;
        width: 30%;
        margin-top: 20%
    }


    .section {
        width: 100%;
        padding: 0 7%;
        display: table;
        margin: 0;
        max-width: none;
        background-color: #373B44;
        height: 100vh;
    }

    .intro {
        height: 90vh;
    }

    .content {
        display: table-cell;
        vertical-align: middle;
    }

    /*h1 {
        font-size: 3em;
        display: block;
        color: white;
        font-weight: 300;
    }

    p {
        font-size: 1.5em;
        font-weight: 500;
        color: #C3CAD9;
    }*/
</style>

 

UserRegistration/Views/MyWelcome/Test.cshtml
@{
    ViewData["Title"] = "Test";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Test</h2>

UserRegistration/Views/MyWelcome/UploadDocuments.cshtml
@{
    ViewData["Title"] = "UploadDocuments";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

 